### ISSUE TITLE
Can't open app (0xc000007b

### ISSUE THREAD

**Issue by filipovskis** [birthdates/Lua-Obfuscator#1]
0xc000007b error when trying to open .exe file, before that was error with ucrtbased.dll, but I fixed this by downloading this dll.
![image](https://user-images.githubusercontent.com/48033052/88718914-24d59f00-d12b-11ea-8b71-3a4bf5abbca5.png)

**Comment by birthdates** [comment]
This isn't an issue, rather the fact you havent't downloaded vcredist. You can find a download link [here](https://support.microsoft.com/en-ca/help/2977003/the-latest-supported-visual-c-downloads).
