### ISSUE TITLE
Impossible to run it

### ISSUE THREAD

**Issue by DarkSide0fTheCode** [birthdates/Lua-Obfuscator#2]
Hi, when i start the .exe it gaves me Error Code 0xc000007b. I installed both x86 and x64 vcredist that you linked in the description. I also tried to open the project in Visual Studio but it's the same. Also tried to run it on a clean OS but nothing seems to work :(

**Comment by birthdates** [comment]
Try running the compatibility troubleshooter and reply with the results

**Comment by DarkSide0fTheCode** [comment]
It suggested me to run it in compatibility mode Windows 8, the result is the same. Apart from this it didn't offered me other solutions

**Comment by birthdates** [comment]
> It suggested me to run it in compatibility mode Windows 8, the result is the same. Apart from this it didn't offered me other solutions

Can you take a screenshot of the error?

**Comment by DarkSide0fTheCode** [comment]
Sure.
![errorscreen](https://user-images.githubusercontent.com/49038688/91437469-3e712000-e86a-11ea-851b-fe6b0873f523.png)

[EN] The application was unable to start 0xc000007b. Click ok to close the application

**Comment by birthdates** [comment]
Do you have a 32-bit system by chance? If not, are you sure you've downloaded [these](https://aka.ms/vs/16/release/vc_redist.x64.exe)?

**Comment by DarkSide0fTheCode** [comment]
My system is x64, By the way i first installed both vc_redist.x64 and vc_redist.x86. I tried on three different PC, two notebooks and 1 desktop. Same error. After installing the vcredist you linked it gives missing .dll on vcruntime140d.dll and ucrtbased.dll. I downloaded them and put in the system32 and systemwow64 and the final error its the one in the screenshot. Searching on internet i read that the vcruntime140d.dll is linked to the fact that the program has been compiled in debug mode on VS, idk if this is the case

**Comment by birthdates** [comment]
> My system is x64, By the way i first installed both vc_redist.x64 and vc_redist.x86. I tried on three different PC, two notebooks and 1 desktop. Same error. After installing the vcredist you linked it gives missing .dll on vcruntime140d.dll and ucrtbased.dll. I downloaded them and put in the system32 and systemwow64 and the final error its the one in the screenshot. Searching on internet i read that the vcruntime140d.dll is linked to the fact that the program has been compiled in debug mode on VS, idk if this is the case

You were right, I was on Debug mode the entire time 🤦‍♂️. Very sorry.
