### ISSUE TITLE
obfuscated lua doesn't run

### ISSUE THREAD

**Issue by Jagohu** [birthdates/Lua-Obfuscator#4]
Hi,

I have used your code to obfuscate my LUA below, but loading it to the simulator "DCS World", it doesn't work anymore.
Do you have any idea what could be wrong? The script runs fine when not obfuscated.
Thanks a lot!

![image](https://user-images.githubusercontent.com/35196588/97318027-b7d9be80-186b-11eb-8367-158c8444af66.png)

```
local staticObj = {
	["heading"] = 4.3458698374659,
	["groupId"] = 999,
	["shape_name"] = "rezky",
	["type"] = "REZKY",
	["unitId"] = 998,
	["rate"] = 100,
	["name"] = "Iran_BandarAbbas_Alvand-class-3",
	["category"] = "Ships",
	["y"] = -2685.7201420976,
	["x"] = 107644.82150389,
	["dead"] = false,
	["hidden"] = true,
}

coalition.addStaticObject(34, staticObj)
--Bandar Abbas port, check if hidden on map
```
Which results in:
`load("\108\111\99\97\108\32\115\116\97\116\105\99\79\98\106\32\61\32\123\10\9\91\34\104\101\97\100\105\110\103\34\93\32\61\32\52\46\51\52\53\56\54\57\56\51\55\52\54\53\57\44\10\9\91\34\103\114\111\117\112\73\100\34\93\32\61\32\57\57\57\44\10\9\91\34\115\104\97\112\101\95\110\97\109\101\34\93\32\61\32\34\114\101\122\107\121\34\44\10\9\91\34\116\121\112\101\34\93\32\61\32\34\82\69\90\75\89\34\44\10\9\91\34\117\110\105\116\73\100\34\93\32\61\32\57\57\56\44\10\9\91\34\114\97\116\101\34\93\32\61\32\49\48\48\44\10\9\91\34\110\97\109\101\34\93\32\61\32\34\73\114\97\110\95\66\97\110\100\97\114\65\98\98\97\115\95\65\108\118\97\110\100\45\99\108\97\115\115\45\51\34\44\10\9\91\34\99\97\116\101\103\111\114\121\34\93\32\61\32\34\83\104\105\112\115\34\44\10\9\91\34\121\34\93\32\61\32\45\50\54\56\53\46\55\50\48\49\52\50\48\57\55\54\44\10\9\91\34\120\34\93\32\61\32\49\48\55\54\52\52\46\56\50\49\53\48\51\56\57\44\10\9\91\34\100\101\97\100\34\93\32\61\32\102\97\108\115\101\44\10\9\91\34\104\105\100\100\101\110\34\93\32\61\32\116\114\117\101\44\10\125\10\99\111\97\108\105\116\105\111\110\46\97\100\100\83\116\97\116\105\99\79\98\106\101\99\116\40\51\52\44\32\115\116\97\116\105\99\79\98\106\41\10\45\45\66\97\110\100\97\114\32\65\98\98\97\115\32\112\111\114\116\44\32\99\104\101\99\107\32\105\102\32\104\105\100\100\101\110\32\111\110\32\109\97\112\10")()`

**Comment by birthdates** [comment]
> Hi,
> 
> I have used your code to obfuscate my LUA below, but loading it to the simulator "DCS World", it doesn't work anymore.
> Do you have any idea what could be wrong? The script runs fine when not obfuscated.
> Thanks a lot!
> 
> ![image](https://user-images.githubusercontent.com/35196588/97318027-b7d9be80-186b-11eb-8367-158c8444af66.png)
> 
> ```
> local staticObj = {
> 	["heading"] = 4.3458698374659,
> 	["groupId"] = 999,
> 	["shape_name"] = "rezky",
> 	["type"] = "REZKY",
> 	["unitId"] = 998,
> 	["rate"] = 100,
> 	["name"] = "Iran_BandarAbbas_Alvand-class-3",
> 	["category"] = "Ships",
> 	["y"] = -2685.7201420976,
> 	["x"] = 107644.82150389,
> 	["dead"] = false,
> 	["hidden"] = true,
> }
> 
> coalition.addStaticObject(34, staticObj)
> --Bandar Abbas port, check if hidden on map
> ```
> 
> Which results in:
> `load("\108\111\99\97\108\32\115\116\97\116\105\99\79\98\106\32\61\32\123\10\9\91\34\104\101\97\100\105\110\103\34\93\32\61\32\52\46\51\52\53\56\54\57\56\51\55\52\54\53\57\44\10\9\91\34\103\114\111\117\112\73\100\34\93\32\61\32\57\57\57\44\10\9\91\34\115\104\97\112\101\95\110\97\109\101\34\93\32\61\32\34\114\101\122\107\121\34\44\10\9\91\34\116\121\112\101\34\93\32\61\32\34\82\69\90\75\89\34\44\10\9\91\34\117\110\105\116\73\100\34\93\32\61\32\57\57\56\44\10\9\91\34\114\97\116\101\34\93\32\61\32\49\48\48\44\10\9\91\34\110\97\109\101\34\93\32\61\32\34\73\114\97\110\95\66\97\110\100\97\114\65\98\98\97\115\95\65\108\118\97\110\100\45\99\108\97\115\115\45\51\34\44\10\9\91\34\99\97\116\101\103\111\114\121\34\93\32\61\32\34\83\104\105\112\115\34\44\10\9\91\34\121\34\93\32\61\32\45\50\54\56\53\46\55\50\48\49\52\50\48\57\55\54\44\10\9\91\34\120\34\93\32\61\32\49\48\55\54\52\52\46\56\50\49\53\48\51\56\57\44\10\9\91\34\100\101\97\100\34\93\32\61\32\102\97\108\115\101\44\10\9\91\34\104\105\100\100\101\110\34\93\32\61\32\116\114\117\101\44\10\125\10\99\111\97\108\105\116\105\111\110\46\97\100\100\83\116\97\116\105\99\79\98\106\101\99\116\40\51\52\44\32\115\116\97\116\105\99\79\98\106\41\10\45\45\66\97\110\100\97\114\32\65\98\98\97\115\32\112\111\114\116\44\32\99\104\101\99\107\32\105\102\32\104\105\100\100\101\110\32\111\110\32\109\97\112\10")()`

It seems DCS World doesn't support load. Try changing `load` to `loadstring`

**Comment by Jagohu** [comment]
Like that it works, perfect, thank you very much!
